version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 786986461513.dkr.ecr.ap-southeast-2.amazonaws.com/youtube
  post_build:
    commands:
      - docker push 786986461513.dkr.ecr.ap-southeast-2.amazonaws.com/youtube
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' 786986461513.dkr.ecr.ap-southeast-2.amazonaws.com/youtube > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
